services:
  db-dev:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:${DEV_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DEV_NAME}

  db-prod:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:${PROD_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${PROD_NAME}
    volumes:
      - pgdata-local:/var/lib/postgresql/data 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# This top-level block tells Docker to actually create the named volume
volumes:
  pgdata-local:
